language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0

before_install:
    - composer self-update

install:
    - composer install --optimize-autoloader --no-interaction

script: ./vendor/bin/phpunit --coverage-text
